name: markdownlinter


on:
  pull_request:
   branches:
   - development


jobs:
 build:
   name: Lint Markdown PR
   runs-on: ubuntu-latest
   
   steps:
    - uses: actions/checkout@v1
      with:
       ref: ${{ github.head_ref }}
    - uses: actions/setup-node@master
    - name: lint all markdownfiles
      env:
          VALIDATE_ALL_CODEBASE: false
      run: |
       npm install
       node_modules/.bin/markdownlint ./ --ignore node_modules
